kind: Deployment
spec:
    name: nginx
    image: nginx:alpine
    replicas: 3
    resources:
        cpu: 100m
        memory: 128Mi
    rolling_update:
        max_surge: 1
        max_unavailable: 0
